apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: postgresql
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgresql
  template:
    metadata:
      labels:
        name: postgresql
    spec:
      containers:
      - image: docker.io/postgres:9.5
        name: postgresql
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - psql -h 127.0.0.1 -U ${POSTGRES_USER} -q -d ${POSTGRES_DB}
              -c 'SELECT 1'
          failureThreshold: 10
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
        env:
        - name: POSTGRES_USER
          value: quarkus_test
        - name: POSTGRES_PASSWORD
          value: quarkus_test
        - name: POSTGRES_DB
          value: quarkus_test
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresql-data
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgresql
  name: postgresql 
spec:
  ports:
  - port: 5432 
    protocol: TCP
    targetPort: 5432
  selector:
    name: postgresql
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  labels:
    name: postgresql
  name: postgresql
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
